version: 1
project_name: cozyssh

before:
  hooks:
    - npm --prefix frontend install
    - npm --prefix frontend run build

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/cozyssh/main.go
    binary: cozyssh
    flags:
      - -trimpath
    ldflags:
      - -s -w -X cozyssh.version={{.Version}} -X cozyssh.commit={{.Commit}} -X cozyssh.date={{.Date}}

  - id: cozyssh-app
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/cozyssh_windows_app
    binary: cozyssh-app
    flags:
      - -trimpath
    ldflags:
      - -s -w -H windowsgui -X cozyssh.version={{.Version}} -X cozyssh.commit={{.Commit}} -X cozyssh.date={{.Date}}
archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
