version: 2
project_name: cozyssh

builds:
  - id: cozyssh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/cozyssh/main.go
    binary: cozyssh
    flags:
      - -trimpath
    ldflags:
      - -s -w -X cozyssh.Version={{.Version}} -X cozyssh.Commit={{.Commit}} -X cozyssh.Date={{.Date}}

  - id: cozyssh-app
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/cozyssh_windows_app
    binary: cozyssh-app
    flags:
      - -trimpath
    ldflags:
      - -s -w -H windowsgui -X cozyssh.Version={{.Version}} -X cozyssh.Commit={{.Commit}} -X cozyssh.Date={{.Date}}

archives:
  - id: cozyssh
    builds:
      - cozyssh
    format: zip
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Env.I18N_SUFFIX }}

  - id: cozyssh-app
    builds:
      - cozyssh-app
    format: zip
    name_template: >-
      {{ .ProjectName }}-app-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Env.I18N_SUFFIX }}

checksum:
  # Keeps checksum files separate so they don't overwrite each other
  name_template: "checksums{{ .Env.I18N_SUFFIX }}.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Tells GoReleaser explicitly to keep existing notes on multi-pass uploads
release:
  mode: keep-existing

changelog:
  disable: "{{ .Env.DISABLE_CHANGELOG }}" # Dynamically skipped in pass 2
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
